// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTask(arg1) {
  return window['go']['main']['App']['CompleteTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAuthToken() {
  return window['go']['main']['App']['GetAuthToken']();
}

export function GetDailyReport(arg1) {
  return window['go']['main']['App']['GetDailyReport'](arg1);
}

export function GetDeveloperInfo() {
  return window['go']['main']['App']['GetDeveloperInfo']();
}

export function GetRunningTimer() {
  return window['go']['main']['App']['GetRunningTimer']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetTrayMenu() {
  return window['go']['main']['App']['GetTrayMenu']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWorklogs(arg1) {
  return window['go']['main']['App']['GetWorklogs'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartTimer(arg1) {
  return window['go']['main']['App']['StartTimer'](arg1);
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}

export function UncompleteTask(arg1) {
  return window['go']['main']['App']['UncompleteTask'](arg1);
}
