// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {menu} from '../models';

export function CompleteTask(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAuthToken():Promise<string>;

export function GetDailyReport(arg1:string):Promise<Array<models.ReportRow>>;

export function GetDeveloperInfo():Promise<main.DeveloperInfo>;

export function GetRunningTimer():Promise<models.Worklog>;

export function GetServerPort():Promise<number>;

export function GetTask(arg1:string):Promise<models.Task>;

export function GetTasks():Promise<Array<models.Task>>;

export function GetTheme():Promise<string>;

export function GetTrayMenu():Promise<menu.Menu>;

export function GetVersion():Promise<string>;

export function GetWorklogs(arg1:string):Promise<Array<models.Worklog>>;

export function OpenFolder(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartTimer(arg1:string):Promise<void>;

export function StopTimer():Promise<models.Worklog>;

export function UncompleteTask(arg1:string):Promise<void>;
